"""
Architecture Design Document export router.
"""

from fastapi import APIRouter
from typing import Dict, Any

router = APIRouter(prefix="/api/export", tags=["Design Document Export"])

@router.post("/markdown")
def export_markdown_spec(data: Dict[str, Any]):
    """Generate a clean, professional Architecture Decision Record (ADR) in Markdown."""
    spec = data.get("spec", {})
    rec = data.get("recommended", {})
    tradeoffs = data.get("serviceTradeoffs", {})
    cost_drivers = data.get("costDrivers", [])
    nodes = data.get("architectureNodes", [])

    md = f"""# Cloud Architecture Decision Document (ADR)
Generated by Cloud AI Architect Engine
Date: {data.get("timestamp", "2026-09-24")}

---

## 1. Executive Summary & Recommended Stack
- **Primary Cloud Provider**: {rec.get("provider", "Multi-Cloud")}
- **Architecture Paradigm**: {rec.get("stack", "Microservices / Containerized")}
- **Projected Monthly Budget**: {rec.get("monthlyCost", 0):,.2f} {rec.get("currency", "USD")}
- **System Suitability Index**: {rec.get("score", 90)}/100

---

## 2. Workload & Operational Parameters
- **Monthly Active Users**: {spec.get("monthlyUsers", 0):,}
- **Throughput Profile**: {spec.get("readOpsPerSec", 0)} reads/sec | {spec.get("writeOpsPerSec", 0)} writes/sec
- **Data Footprint**: {spec.get("storageGB", 0)} GB Storage | {spec.get("egressGB", 0)} GB Network Egress/month
- **Target Latency**: p95 <= {spec.get("maxLatencyMs", 150)} ms
- **High Availability & Compliance**: {spec.get("redundancyTier", "single-az")} | {spec.get("regionalCompliance", "none").upper()}

---

## 3. Dataflow & Component Pipeline
"""
    for node in nodes:
        stage = node.get('stage') or node.get('id', '')
        category = node.get('category') or node.get('layer', '')
        component = node.get('component') or node.get('name', '')
        details = node.get('details') or f"{node.get('spec', '')} - {node.get('role', '')}"
        protocol = node.get('protocol', 'TCP/IP')
        md += f"### Stage {stage}: {category}\n"
        md += f"- **Component**: {component}\n"
        md += f"- **Operational Specs**: {details}\n"
        md += f"- **Protocol / Interface**: `{protocol}`\n\n"

    md += """---

## 4. Cost Driver Breakdown
| Infrastructure Layer | Budget Allocation | Primary Driver | Optimization Recommendation |
| :--- | :--- | :--- | :--- |
"""
    for cd in cost_drivers:
        layer = cd.get('layer') or cd.get('name', 'Tier')
        allocation = cd.get('allocation') or f"{cd.get('percentage', 0)}%"
        driver = cd.get('driver') or cd.get('explanation', '')
        strategy = cd.get('strategy') or f"Targeted: ${cd.get('amountUSD', 0)}/mo"
        md += f"| **{layer}** | {allocation} | {driver} | {strategy} |\n"

    md += """
---

## 5. Architectural Trade-offs & Decision Heuristics
"""
    if isinstance(tradeoffs, dict):
        md += f"- **Core Heuristic**: {tradeoffs.get('primaryHeuristic', 'N/A')}\n"
        md += f"- **Selection Rationale**: {tradeoffs.get('selectionRationale', 'N/A')}\n\n"
        md += "### Rejected Alternatives\n"
        for alt in tradeoffs.get("alternativesEvaluated", []):
            md += f"- **{alt.get('alternative')}**: Rejected because {alt.get('whyRejected')} *Trigger condition to switch*: {alt.get('switchCondition')}\n"
    elif isinstance(tradeoffs, list):
        for t in tradeoffs:
            md += f"### {t.get('component', 'Component')}\n"
            md += f"- **Selected Service**: {t.get('selectedService', '')}\n"
            md += f"- **Rationale**: {t.get('whySelected', '')}\n"
            md += f"- **Alternative**: {t.get('alternativeService', '')}\n"
            md += f"- **Trade-off**: {t.get('alternativeTradeoff', '')}\n"
            md += f"- **Decision Rule**: {t.get('decisionRule', '')}\n\n"

    return {
        "filename": f"Architecture_Specification_{rec.get('providerId', 'cloud')}.md",
        "markdown": md
    }
