"""
Cloud AI Architect V2 — Master Cloud Providers Database (17 Providers)
Single Source of Truth for all 17 Cloud Providers, Services, Categories, Capabilities,
Regional Coverage, and Free-Tier Programs.

Canonical Providers:
1.  aws          - Amazon Web Services (AWS)
2.  gcp          - Google Cloud Platform (GCP)
3.  azure        - Microsoft Azure
4.  hetzner      - Hetzner Cloud
5.  oci          - Oracle Cloud Infrastructure (OCI)
6.  digitalocean - DigitalOcean
7.  linode       - Linode (Akamai Connected Cloud)
8.  vultr        - Vultr
9.  ovhcloud     - OVHcloud
10. alibaba      - Alibaba Cloud (Aliyun)
11. scaleway     - Scaleway
12. render       - Render
13. flyio        - Fly.io
14. railway      - Railway
15. proxmox      - Proxmox VE
16. openstack    - OpenStack
17. nutanix      - Nutanix Enterprise Cloud
"""

from typing import Dict, Any, List

CLOUD_PROVIDERS: List[Dict[str, Any]] = [
    # --- BIG 3 HYPERSCALERS ---
    {
        "id": "azure",
        "name": "Microsoft Azure",
        "shortName": "Azure",
        "category": "Big 3 Hyperscaler",
        "badge": "Enterprise Core & Hybrid Champion",
        "country": "Global (60+ Regions, 300+ Datacenters)",
        "starterSpec": "B1s Burstable (1 vCPU, 1 GB RAM, 32 GB Premium SSD)",
        "tagline": "The premier enterprise cloud for Windows Server, SQL Server, Microsoft Entra ID (Azure AD), and M365.",
        "description": "Azure provides unmatched first-party integration for Windows, SQL Server, Microsoft Entra ID, and hybrid on-premises networking via ExpressRoute.",
        "costMonthlyUSD": 52.00,
        "cost24HrUSD": 1.75,
        "freeAllowance": "$200 trial credits (30 days) + 12 Months Free Services (750 hrs B1s, 64GB SSD, 5GB Blob Storage)",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "100 GB Free Egress worldwide ($0.087/GB thereafter)",
        "capabilities": {
            "windowsWorkloads": 98,
            "sqlServerSupport": 100,
            "entraIdIntegration": 100,
            "microsoftEcosystem": 100,
            "hybridConnectivity": 96,
            "kubernetes": 90,
            "serverlessContainers": 88,
            "gpuInference": 92,
            "websocketsRealtime": 92,
            "mediaProcessing": 85,
            "relationalPostgres": 90,
            "relationalMySQL": 88,
            "oracleDatabase": 72,
            "cachingRedis": 92,
            "scheduledJobsQueues": 94,
            "developerSimplicity": 62,
            "costEfficiencyPerDollar": 68,
            "complianceCoverage": ["hipaa", "soc2", "pci-dss", "gdpr", "rbi-india", "fedramp"],
            "regions": ["india", "us-east", "us-west", "europe", "apac", "latam"]
        },
        "services": {
            "dns": "Azure DNS & Traffic Manager",
            "loadBalancer": "Azure Application Gateway (WAF v2)",
            "compute": "Azure Virtual Machines & Container Apps",
            "containerOrchestrator": "Azure Kubernetes Service (AKS)",
            "serverless": "Azure Functions (v4 Isolated)",
            "database": {
                "sqlServer": "Azure SQL Managed Instance / Azure SQL DB",
                "postgres": "Azure Database for PostgreSQL Flexible Server",
                "mysql": "Azure Database for MySQL Flexible Server",
                "oracle": "Azure VM with Oracle Linux / Azure OCI Interconnect",
                "nosql": "Azure Cosmos DB"
            },
            "cache": "Azure Cache for Redis (Enterprise Tier)",
            "objectStorage": "Azure Blob Storage (Hot / Cool GRS)",
            "queue": "Azure Service Bus & Event Grid",
            "scheduledJobs": "Azure Functions Timer Trigger / Logic Apps",
            "gpuInstance": "Azure NCasT4_v3 / NDv4 A100 Tensor Core",
            "hybridGateway": "Azure ExpressRoute Gateway & VPN Gateway",
            "identity": "Microsoft Entra ID (Azure Active Directory)",
            "monitoring": "Azure Monitor & Application Insights",
            "cdn": "Azure Front Door",
            "security": "Microsoft Defender for Cloud & Key Vault"
        },
        "pricing": {
            "computePerHourVCPU": 0.0416,
            "ramPerHourGB": 0.0056,
            "dbBaseMonthly": 32.00,
            "sqlServerLicenseMultiplier": 1.45,
            "objectStoragePerGBMonth": 0.018,
            "egressPerGB": 0.087,
            "cacheBaseMonthly": 28.00,
            "gpuHourlyRate": 1.25,
            "hybridGatewayMonthly": 75.00
        },
        "pros": [
            "Flawless Active Directory, Entra ID, and Windows Server licensing advantages via Azure Hybrid Benefit",
            "ExpressRoute private 100Gbps cross-connect for seamless corporate datacenter federation",
            "Mature enterprise governance, compliance (RBI India, HIPAA, FedRAMP), and SLAs"
        ],
        "cons": [
            "Heavy portal interface with complex nested blade navigation",
            "B-series burst credit depletion under sustained loads throttles CPU"
        ],
        "bestFor": "Enterprises built on .NET, Windows Server, SQL Server, Active Directory, Office 365, and hybrid on-prem datacenters"
    },
    {
        "id": "aws",
        "name": "Amazon Web Services (AWS)",
        "shortName": "AWS",
        "category": "Big 3 Hyperscaler",
        "badge": "Hyperscale Pioneer & Deep Ecosystem",
        "country": "Global (34 Regions, 105+ AZs)",
        "starterSpec": "t4g.small (2 vCPU, 2 GB ARM) or t3.small, 20 GB EBS",
        "tagline": "The broadest and most adopted cloud with deep operational reliability and 300+ managed services.",
        "description": "AWS delivers the deepest set of infrastructure and application services, unmatched regional coverage, and battle-tested global scale for enterprise and consumer SaaS.",
        "costMonthlyUSD": 78.00,
        "cost24HrUSD": 2.60,
        "freeAllowance": "12 Months Free Tier (750 hrs t2/t3.micro, 5GB S3, 1M Lambda invocations)",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "100 GB Free Egress (Then $0.09/GB egress fees)",
        "capabilities": {
            "windowsWorkloads": 78,
            "sqlServerSupport": 82,
            "entraIdIntegration": 35,
            "microsoftEcosystem": 40,
            "hybridConnectivity": 94,
            "kubernetes": 94,
            "serverlessContainers": 94,
            "gpuInference": 95,
            "websocketsRealtime": 95,
            "mediaProcessing": 96,
            "relationalPostgres": 96,
            "relationalMySQL": 95,
            "oracleDatabase": 80,
            "cachingRedis": 95,
            "scheduledJobsQueues": 98,
            "developerSimplicity": 60,
            "costEfficiencyPerDollar": 65,
            "complianceCoverage": ["hipaa", "soc2", "pci-dss", "gdpr", "rbi-india", "fedramp"],
            "regions": ["india", "us-east", "us-west", "europe", "apac", "latam"]
        },
        "services": {
            "dns": "Amazon Route 53 (Latency & Geo Routing)",
            "loadBalancer": "AWS Application Load Balancer (ALB)",
            "compute": "Amazon EC2 (c6g/c7g) & AWS ECS Fargate",
            "containerOrchestrator": "Amazon Elastic Kubernetes Service (EKS)",
            "serverless": "AWS Lambda (arm64 Graviton)",
            "database": {
                "sqlServer": "Amazon RDS for SQL Server (Multi-AZ)",
                "postgres": "Amazon Aurora Serverless v2 (PostgreSQL)",
                "mysql": "Amazon Aurora MySQL",
                "oracle": "Amazon RDS for Oracle",
                "nosql": "Amazon DynamoDB"
            },
            "cache": "Amazon ElastiCache for Redis (Cluster Mode)",
            "objectStorage": "Amazon S3 Standard (Intelligent-Tiering)",
            "queue": "Amazon SQS & Amazon EventBridge",
            "scheduledJobs": "Amazon EventBridge Scheduler + ECS/Lambda",
            "gpuInstance": "Amazon EC2 G5 (NVIDIA A10G) / P4de (A100)",
            "hybridGateway": "AWS Direct Connect & AWS Transit Gateway",
            "identity": "AWS IAM Identity Center / Amazon Cognito",
            "monitoring": "Amazon CloudWatch & AWS X-Ray",
            "cdn": "Amazon CloudFront",
            "security": "AWS Shield, WAF & AWS KMS"
        },
        "pricing": {
            "computePerHourVCPU": 0.0405,
            "ramPerHourGB": 0.0054,
            "dbBaseMonthly": 35.00,
            "sqlServerLicenseMultiplier": 2.20,
            "objectStoragePerGBMonth": 0.023,
            "egressPerGB": 0.090,
            "cacheBaseMonthly": 30.00,
            "gpuHourlyRate": 1.30,
            "hybridGatewayMonthly": 85.00
        },
        "pros": [
            "Broadest ecosystem of managed services, serverless tools, and third-party integrations",
            "Aurora Serverless v2 delivers instant autoscaling for relational databases",
            "Proven hyperscale reliability and global availability zones"
        ],
        "cons": [
            "Aggressive $0.09/GB egress fees and idle NAT Gateway tax ($33/mo per AZ)",
            "Significantly higher licensing costs for Windows/SQL Server than Azure"
        ],
        "bestFor": "Enterprise corporations, massive scale systems, government agencies, global SaaS"
    },
    {
        "id": "gcp",
        "name": "Google Cloud Platform (GCP)",
        "shortName": "Google Cloud",
        "category": "Big 3 Hyperscaler",
        "badge": "AI/ML & Kubernetes Pioneer",
        "country": "Global (40 Regions, 121+ AZs)",
        "starterSpec": "e2-micro (2 vCPU, 1 GB) or Cloud Run Serverless Containers",
        "tagline": "The cloud of choice for Kubernetes-native architectures, container serverless, BigQuery, and generative AI.",
        "description": "Google Cloud excels at containerized workloads with Google Kubernetes Engine (GKE) and Cloud Run, alongside state-of-the-art AI infrastructure and BigQuery analytics.",
        "costMonthlyUSD": 38.00,
        "cost24HrUSD": 1.25,
        "freeAllowance": "$300 free trial credits (90 days) + Perpetual Free Tier (e2-micro VM, 2M Cloud Run requests, 5GB GCS)",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "1 GB to 10 GB Free depending on region ($0.08 - $0.12/GB overage)",
        "capabilities": {
            "windowsWorkloads": 65,
            "sqlServerSupport": 70,
            "entraIdIntegration": 30,
            "microsoftEcosystem": 32,
            "hybridConnectivity": 86,
            "kubernetes": 99,
            "serverlessContainers": 98,
            "gpuInference": 98,
            "websocketsRealtime": 88,
            "mediaProcessing": 90,
            "relationalPostgres": 94,
            "relationalMySQL": 90,
            "oracleDatabase": 60,
            "cachingRedis": 90,
            "scheduledJobsQueues": 92,
            "developerSimplicity": 74,
            "costEfficiencyPerDollar": 72,
            "complianceCoverage": ["hipaa", "soc2", "pci-dss", "gdpr", "rbi-india", "fedramp"],
            "regions": ["india", "us-east", "us-west", "europe", "apac", "latam"]
        },
        "services": {
            "dns": "Google Cloud DNS",
            "loadBalancer": "Cloud Load Balancing (Global Anycast)",
            "compute": "Google Cloud Run & Compute Engine",
            "containerOrchestrator": "Google Kubernetes Engine (GKE Autopilot)",
            "serverless": "Cloud Run Functions (2nd Gen)",
            "database": {
                "sqlServer": "Cloud SQL for SQL Server",
                "postgres": "Cloud SQL for PostgreSQL / AlloyDB",
                "mysql": "Cloud SQL for MySQL",
                "oracle": "Bare Metal Solution for Oracle",
                "nosql": "Cloud Firestore / Bigtable"
            },
            "cache": "Memorystore for Redis",
            "objectStorage": "Google Cloud Storage (Standard)",
            "queue": "Cloud Pub/Sub & Cloud Tasks",
            "scheduledJobs": "Cloud Scheduler + Cloud Run Jobs",
            "gpuInstance": "Compute Engine G2 (NVIDIA L4) / A2 (A100)",
            "hybridGateway": "Dedicated Interconnect & Cloud VPN",
            "identity": "Google Cloud Identity / Identity Platform",
            "monitoring": "Google Cloud Operations (formerly Stackdriver)",
            "cdn": "Cloud CDN & Media CDN",
            "security": "Cloud Armor & Secret Manager"
        },
        "pricing": {
            "computePerHourVCPU": 0.0380,
            "ramPerHourGB": 0.0051,
            "dbBaseMonthly": 28.00,
            "sqlServerLicenseMultiplier": 2.15,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.085,
            "cacheBaseMonthly": 25.00,
            "gpuHourlyRate": 1.15,
            "hybridGatewayMonthly": 70.00
        },
        "pros": [
            "Best-in-class Kubernetes engine (GKE Autopilot) and container serverless (Cloud Run)",
            "Google Global Anycast networking provides sub-20ms edge routing worldwide",
            "Unrivaled data analytics with BigQuery and native Vertex AI model hosting"
        ],
        "cons": [
            "Weaker native integration for legacy Microsoft enterprise tooling",
            "High egress bandwidth charges outside the small 1GB free tier"
        ],
        "bestFor": "Containerized microservices, AI/ML inference workloads, scale-to-zero web apps, Kubernetes clusters"
    },

    # --- MAJOR ALTERNATIVE DEVELOPER CLOUDS ---
    {
        "id": "hetzner",
        "name": "Hetzner Cloud",
        "shortName": "Hetzner",
        "category": "Alternative IaaS",
        "badge": "Extreme Price-to-Performance",
        "country": "Germany / Finland / US / Singapore",
        "starterSpec": "CX22 (2 vCPUs, 4 GB RAM, 40 GB NVMe, 20 TB Transfer)",
        "tagline": "Unbeatable European compute value, dedicated NVMe servers, and massive 20TB included traffic per host.",
        "description": "Hetzner Cloud delivers the highest raw compute, RAM, and NVMe disk performance per dollar on the market, ideal for cost-conscious, bootstrapped, or European-headquartered systems.",
        "costMonthlyUSD": 4.10,
        "cost24HrUSD": 0.15,
        "freeAllowance": "Permanently 70-85% cheaper baseline; occasional €20 community vouchers",
        "creditCardReq": "Yes (Strict Passport/ID KYC)",
        "bandwidthIncluded": "20 TB Free per server (€1.00/TB overage — lowest in industry)",
        "capabilities": {
            "windowsWorkloads": 30,
            "sqlServerSupport": 22,
            "entraIdIntegration": 10,
            "microsoftEcosystem": 12,
            "hybridConnectivity": 35,
            "kubernetes": 78,
            "serverlessContainers": 65,
            "gpuInference": 40,
            "websocketsRealtime": 84,
            "mediaProcessing": 82,
            "relationalPostgres": 80,
            "relationalMySQL": 78,
            "oracleDatabase": 10,
            "cachingRedis": 80,
            "scheduledJobsQueues": 76,
            "developerSimplicity": 90,
            "costEfficiencyPerDollar": 99,
            "complianceCoverage": ["gdpr"],
            "regions": ["europe", "us-east"]
        },
        "services": {
            "dns": "Hetzner DNS Console",
            "loadBalancer": "Hetzner Load Balancer (LB11 / LB21)",
            "compute": "Hetzner Cloud Servers (CPX / CCX Dedicated)",
            "containerOrchestrator": "k3s / kubeadm on Hetzner Cloud (with hcloud-csi)",
            "serverless": "Self-hosted OpenFaaS / Knative",
            "database": {
                "sqlServer": "Self-managed SQL Server on Windows VM",
                "postgres": "Self-managed PostgreSQL on local NVMe / Managed DB partner",
                "mysql": "Self-managed MySQL on local NVMe",
                "oracle": "Not Supported",
                "nosql": "Self-hosted ScyllaDB / MongoDB"
            },
            "cache": "Self-hosted Redis with persistence",
            "objectStorage": "Hetzner Storage Box (WebDAV/SFTP) or MinIO on NVMe",
            "queue": "Self-hosted RabbitMQ / Redis Streams",
            "scheduledJobs": "Systemd Timers / Cron on Cloud Servers",
            "gpuInstance": "Hetzner Server Auction (Custom GPU Dedicated)",
            "hybridGateway": "WireGuard / StrongSwan IPSec Site-to-Site Tunnel",
            "identity": "Keycloak / Authelia on Hetzner",
            "monitoring": "Prometheus & Grafana on Hetzner Cloud",
            "cdn": "Cloudflare integration recommended",
            "security": "Hetzner Cloud Firewall"
        },
        "pricing": {
            "computePerHourVCPU": 0.0095,
            "ramPerHourGB": 0.0016,
            "dbBaseMonthly": 10.00,
            "sqlServerLicenseMultiplier": 3.00,
            "objectStoragePerGBMonth": 0.005,
            "egressPerGB": 0.001,
            "cacheBaseMonthly": 8.00,
            "gpuHourlyRate": 0.80,
            "hybridGatewayMonthly": 10.00
        },
        "pros": [
            "Incredible raw compute power per dollar (3x to 5x cheaper than hyperscalers)",
            "20 TB of free outbound traffic included per cloud server, virtually eliminating egress shock",
            "Strict European GDPR compliance and low environmental footprint"
        ],
        "cons": [
            "No native Asian/Indian datacenters (primarily Germany, Finland, and US East/West)",
            "Requires more self-managed DevOps tooling; lacks turnkey managed PaaS services"
        ],
        "bestFor": "High-bandwidth streaming, SaaS backends, multi-node Kubernetes, bulk compute on a budget"
    },
    {
        "id": "oci",
        "name": "Oracle Cloud Infrastructure (OCI)",
        "shortName": "Oracle Cloud",
        "category": "Alternative IaaS / Free Tier Leader",
        "badge": "Database & Perpetual Free Tier",
        "country": "Global (US, India, Europe, Asia)",
        "starterSpec": "4 Ampere A1 ARM Cores, 24 GB RAM, 200 GB NVMe",
        "tagline": "Superior database economics, Autonomous Database, generous free bandwidth, and fast bare-metal compute.",
        "description": "OCI offers superior price-performance for enterprise databases, 10TB/month of free egress bandwidth, Oracle Autonomous Database, and high-performance Ampere and GPU clusters.",
        "costMonthlyUSD": 0.00,
        "cost24HrUSD": 0.00,
        "freeAllowance": "Perpetual Always Free (4 ARM cores, 24GB RAM, 200GB storage, 10 TB egress) + $300 30-day trial",
        "creditCardReq": "Yes (Credit card for verification)",
        "bandwidthIncluded": "10 TB Outbound Data Transfer Free/mo ($0.0085/GB thereafter)",
        "capabilities": {
            "windowsWorkloads": 70,
            "sqlServerSupport": 72,
            "entraIdIntegration": 38,
            "microsoftEcosystem": 42,
            "hybridConnectivity": 88,
            "kubernetes": 84,
            "serverlessContainers": 82,
            "gpuInference": 92,
            "websocketsRealtime": 82,
            "mediaProcessing": 80,
            "relationalPostgres": 86,
            "relationalMySQL": 92,
            "oracleDatabase": 100,
            "cachingRedis": 82,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 65,
            "costEfficiencyPerDollar": 86,
            "complianceCoverage": ["hipaa", "soc2", "pci-dss", "gdpr", "rbi-india", "fedramp"],
            "regions": ["india", "us-east", "us-west", "europe", "apac"]
        },
        "services": {
            "dns": "OCI DNS Service",
            "loadBalancer": "OCI Flexible Load Balancer",
            "compute": "OCI Compute (Ampere A1 / AMD EPYC)",
            "containerOrchestrator": "Oracle Container Engine for Kubernetes (OKE)",
            "serverless": "OCI Functions (Fn Project based)",
            "database": {
                "sqlServer": "OCI Database with SQL Server",
                "postgres": "OCI Database with PostgreSQL",
                "mysql": "MySQL HeatWave Service",
                "oracle": "Oracle Autonomous Database (Serverless)",
                "nosql": "Oracle NoSQL Database Cloud"
            },
            "cache": "OCI Cache with Redis",
            "objectStorage": "OCI Object Storage (Standard Tier)",
            "queue": "OCI Queue & OCI Events",
            "scheduledJobs": "OCI Resource Scheduler / OCI Functions Timer",
            "gpuInstance": "OCI GPU Instances (NVIDIA A10 / A100)",
            "hybridGateway": "OCI FastConnect & IPSec VPN",
            "identity": "OCI IAM Identity Domains",
            "monitoring": "OCI Monitoring & Logging Analytics",
            "cdn": "OCI Web Application Acceleration",
            "security": "OCI Cloud Guard & Vault"
        },
        "pricing": {
            "computePerHourVCPU": 0.0280,
            "ramPerHourGB": 0.0038,
            "dbBaseMonthly": 22.00,
            "sqlServerLicenseMultiplier": 2.00,
            "objectStoragePerGBMonth": 0.025,
            "egressPerGB": 0.0085,
            "cacheBaseMonthly": 20.00,
            "gpuHourlyRate": 1.10,
            "hybridGatewayMonthly": 50.00
        },
        "pros": [
            "10 TB of free outbound data transfer per month, then only $0.0085/GB",
            "Industry standard for Oracle Database and MySQL HeatWave analytics",
            "Very competitive Ampere ARM and AMD EPYC core compute pricing"
        ],
        "cons": [
            "Steeper IAM learning curve and smaller community than AWS/Azure",
            "Popular free regions frequently out of host capacity"
        ],
        "bestFor": "Zero-budget MVP startups, indie hackers, persistent microservices, enterprise Oracle workloads"
    },
    {
        "id": "digitalocean",
        "name": "DigitalOcean",
        "shortName": "DigitalOcean",
        "category": "Alternative IaaS",
        "badge": "Developer Simplicity & Velocity",
        "country": "Global (15+ Regions, Bangalore BLR1)",
        "starterSpec": "1 vCPU, 1 GB RAM, 25 GB SSD, 1 TB Transfer",
        "tagline": "Simple, predictable cloud infrastructure designed for developers, agile startups, and modern web apps.",
        "description": "DigitalOcean eliminates hyperscaler complexity with clean predictable pricing, straightforward managed PostgreSQL, managed Kubernetes (DOKS), and App Platform.",
        "costMonthlyUSD": 6.00,
        "cost24HrUSD": 0.22,
        "freeAllowance": "$200 Free Credits for 60 Days (GitHub Student Pack grants +$200)",
        "creditCardReq": "Yes (Credit Card or PayPal)",
        "bandwidthIncluded": "1 TB Included Transfer ($0.01/GB overage)",
        "capabilities": {
            "windowsWorkloads": 22,
            "sqlServerSupport": 20,
            "entraIdIntegration": 12,
            "microsoftEcosystem": 15,
            "hybridConnectivity": 30,
            "kubernetes": 82,
            "serverlessContainers": 86,
            "gpuInference": 65,
            "websocketsRealtime": 82,
            "mediaProcessing": 80,
            "relationalPostgres": 88,
            "relationalMySQL": 86,
            "oracleDatabase": 10,
            "cachingRedis": 85,
            "scheduledJobsQueues": 80,
            "developerSimplicity": 98,
            "costEfficiencyPerDollar": 88,
            "complianceCoverage": ["gdpr", "soc2"],
            "regions": ["india", "us-east", "us-west", "europe", "apac"]
        },
        "services": {
            "dns": "DigitalOcean DNS",
            "loadBalancer": "DigitalOcean Load Balancers (HA Proxy based)",
            "compute": "DigitalOcean Droplets & App Platform",
            "containerOrchestrator": "DigitalOcean Kubernetes (DOKS)",
            "serverless": "DigitalOcean Functions",
            "database": {
                "sqlServer": "Custom Docker on Droplet (Self-managed only)",
                "postgres": "DigitalOcean Managed Databases for PostgreSQL",
                "mysql": "DigitalOcean Managed Databases for MySQL",
                "oracle": "Not Supported",
                "nosql": "Managed MongoDB"
            },
            "cache": "DigitalOcean Managed Redis",
            "objectStorage": "DigitalOcean Spaces (S3 compatible + built-in CDN)",
            "queue": "Managed Kafka / Redis Queue",
            "scheduledJobs": "DigitalOcean App Platform Worker / Scheduled Jobs",
            "gpuInstance": "Paperspace by DigitalOcean (H100 / A100 / A4000)",
            "hybridGateway": "VPC Peering & Custom IPSec Gateway on Droplet",
            "identity": "Third-Party OAuth / Auth0 / Supabase",
            "monitoring": "DigitalOcean Monitoring & Alerting",
            "cdn": "Spaces Built-in CDN",
            "security": "Cloud Firewalls (Free)"
        },
        "pricing": {
            "computePerHourVCPU": 0.0180,
            "ramPerHourGB": 0.0028,
            "dbBaseMonthly": 15.00,
            "sqlServerLicenseMultiplier": 3.00,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.010,
            "cacheBaseMonthly": 15.00,
            "gpuHourlyRate": 0.95,
            "hybridGatewayMonthly": 20.00
        },
        "pros": [
            "Exceptional developer experience: spins up in seconds with transparent monthly invoices",
            "Managed PostgreSQL and Redis are rock-solid for startup and medium SaaS",
            "Generous bandwidth pool included with each droplet"
        ],
        "cons": [
            "No native managed SQL Server or enterprise Windows directory integration",
            "Lacks dedicated enterprise private circuits (no DirectConnect/ExpressRoute equiv)"
        ],
        "bestFor": "Rapid SaaS prototyping, software agency client hosting, staging clusters, agency retainers"
    },
    {
        "id": "linode",
        "name": "Linode (Akamai Connected Cloud)",
        "shortName": "Linode",
        "category": "Alternative IaaS",
        "badge": "Akamai Global Edge & Linux Core",
        "country": "Global (Akamai Edge Network, Mumbai)",
        "starterSpec": "1 vCPU, 1 GB RAM, 25 GB SSD, 1 TB Transfer",
        "tagline": "High-performance Linux compute backed by Akamai's distributed global edge network.",
        "description": "Linode combines transparent developer virtual machines with Akamai's content delivery and cybersecurity backbone.",
        "costMonthlyUSD": 5.00,
        "cost24HrUSD": 0.18,
        "freeAllowance": "$100 Free Credits for 60 Days",
        "creditCardReq": "Yes (Strict fraud filtering)",
        "bandwidthIncluded": "1 TB Transfer pooled globally across all nodes",
        "capabilities": {
            "windowsWorkloads": 25,
            "sqlServerSupport": 25,
            "entraIdIntegration": 15,
            "microsoftEcosystem": 18,
            "hybridConnectivity": 40,
            "kubernetes": 80,
            "serverlessContainers": 70,
            "gpuInference": 75,
            "websocketsRealtime": 80,
            "mediaProcessing": 82,
            "relationalPostgres": 84,
            "relationalMySQL": 82,
            "oracleDatabase": 15,
            "cachingRedis": 82,
            "scheduledJobsQueues": 78,
            "developerSimplicity": 92,
            "costEfficiencyPerDollar": 86,
            "complianceCoverage": ["gdpr", "soc2", "pci-dss"],
            "regions": ["india", "us-east", "us-west", "europe", "apac"]
        },
        "services": {
            "dns": "Linode DNS Manager",
            "loadBalancer": "Linode NodeBalancers",
            "compute": "Linode Compute Instances (Dedicated & Shared CPU)",
            "containerOrchestrator": "Linode Kubernetes Engine (LKE)",
            "serverless": "Akamai EdgeWorkers",
            "database": {
                "sqlServer": "Self-managed on VM",
                "postgres": "Linode Managed Databases for PostgreSQL",
                "mysql": "Linode Managed Databases for MySQL",
                "oracle": "Not Supported",
                "nosql": "Managed MongoDB"
            },
            "cache": "Self-managed Redis on Linode",
            "objectStorage": "Linode Object Storage (S3-compatible)",
            "queue": "Self-hosted RabbitMQ / Redis",
            "scheduledJobs": "Cron / Systemd on Linode",
            "gpuInstance": "Linode Dedicated GPU Instances (RTX6000)",
            "hybridGateway": "IPSec VPN / BGP Peering",
            "identity": "OAuth / Keycloak",
            "monitoring": "Linode Longview",
            "cdn": "Akamai Edge Cloud",
            "security": "Cloud Firewalls"
        },
        "pricing": {
            "computePerHourVCPU": 0.0150,
            "ramPerHourGB": 0.0025,
            "dbBaseMonthly": 15.00,
            "sqlServerLicenseMultiplier": 3.00,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.010,
            "cacheBaseMonthly": 15.00,
            "gpuHourlyRate": 1.00,
            "hybridGatewayMonthly": 25.00
        },
        "pros": [
            "High-performance AMD EPYC processors and 24/7 human telephone support included",
            "Seamless Akamai global edge distribution and DDoS shielding",
            "Generous globally pooled bandwidth allocations"
        ],
        "cons": [
            "Strict fraud verification on new signups",
            "Smaller managed PaaS catalog compared to Big 3"
        ],
        "bestFor": "Monolithic Linux backends, self-hosted open-source (GitLab, Nextcloud), edge microservices"
    },
    {
        "id": "vultr",
        "name": "Vultr",
        "shortName": "Vultr",
        "category": "Alternative IaaS",
        "badge": "Global Geographic Footprint & Custom ISO",
        "country": "Global (32+ Datacenters, Mumbai & Delhi)",
        "starterSpec": "1 vCPU, 1 GB RAM, 25 GB NVMe, 1 TB Transfer",
        "tagline": "32+ global datacenter locations, custom OS ISO uploads, high-frequency NVMe, and fractional GPUs.",
        "description": "Vultr stands out with an expansive global datacenter presence in 32+ cities, custom Windows/BSD ISO uploads, high-frequency compute, and on-demand GPU clusters.",
        "costMonthlyUSD": 6.00,
        "cost24HrUSD": 0.22,
        "freeAllowance": "$100 to $250 Free Credits (30 Days) + 100% deposit match up to $100",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "1 TB Transfer calculated per datacenter",
        "capabilities": {
            "windowsWorkloads": 55,
            "sqlServerSupport": 45,
            "entraIdIntegration": 20,
            "microsoftEcosystem": 25,
            "hybridConnectivity": 45,
            "kubernetes": 82,
            "serverlessContainers": 72,
            "gpuInference": 88,
            "websocketsRealtime": 82,
            "mediaProcessing": 84,
            "relationalPostgres": 85,
            "relationalMySQL": 84,
            "oracleDatabase": 15,
            "cachingRedis": 82,
            "scheduledJobsQueues": 78,
            "developerSimplicity": 90,
            "costEfficiencyPerDollar": 86,
            "complianceCoverage": ["gdpr", "soc2", "pci-dss"],
            "regions": ["india", "us-east", "us-west", "europe", "apac", "latam"]
        },
        "services": {
            "dns": "Vultr DNS",
            "loadBalancer": "Vultr Load Balancers",
            "compute": "Vultr Cloud Compute (High Frequency NVMe)",
            "containerOrchestrator": "Vultr Kubernetes Engine (VKE)",
            "serverless": "Vultr Serverless Inference",
            "database": {
                "sqlServer": "Windows Server VM with SQL Server",
                "postgres": "Vultr Managed Databases for PostgreSQL",
                "mysql": "Vultr Managed Databases for MySQL",
                "oracle": "Not Supported",
                "nosql": "Vultr Managed Valkey/Redis"
            },
            "cache": "Vultr Managed Redis",
            "objectStorage": "Vultr Object Storage",
            "queue": "Self-hosted Queues",
            "scheduledJobs": "Cron on Cloud Compute",
            "gpuInstance": "Vultr Cloud GPU (NVIDIA GH200 / A100 / L40S)",
            "hybridGateway": "Direct Connect / Direct Peering",
            "identity": "OAuth / Keycloak",
            "monitoring": "Vultr Metrics",
            "cdn": "Vultr CDN",
            "security": "Native DDoS Mitigation"
        },
        "pricing": {
            "computePerHourVCPU": 0.0160,
            "ramPerHourGB": 0.0026,
            "dbBaseMonthly": 15.00,
            "sqlServerLicenseMultiplier": 2.80,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.010,
            "cacheBaseMonthly": 15.00,
            "gpuHourlyRate": 0.90,
            "hybridGatewayMonthly": 30.00
        },
        "pros": [
            "32+ global datacenter locations including Mumbai and Delhi NCR",
            "Upload any custom Windows, Linux, or BSD operating system ISO",
            "Turnkey access to modern NVIDIA Cloud GPUs (A100, L40S)"
        ],
        "cons": [
            "Bandwidth not globally pooled across regions",
            "Ticketing support is asynchronous with variable turnaround"
        ],
        "bestFor": "Specific geographic routing (Sydney, São Paulo, Tokyo, Mumbai), GPU AI inference, custom OS setups"
    },
    {
        "id": "ovhcloud",
        "name": "OVHcloud",
        "shortName": "OVHcloud",
        "category": "European Hyperscaler",
        "badge": "Unmetered Bandwidth & Anti-DDoS",
        "country": "France / Europe / Canada",
        "starterSpec": "1 vCPU, 2 GB RAM, 40 GB NVMe, 250 Mbps Unmetered",
        "tagline": "100% unmetered public bandwidth, proprietary Anti-DDoS protection, and complete European data sovereignty.",
        "description": "OVHcloud is Europe's largest cloud provider, offering unlimited unmetered bandwidth, bare-metal servers, and immunity from the US CLOUD Act.",
        "costMonthlyUSD": 6.50,
        "cost24HrUSD": 0.26,
        "freeAllowance": "$100 - $200 promo vouchers + 30-day money-back guarantee",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "Unmetered & Unlimited Public Bandwidth (250 Mbps - 1 Gbps)",
        "capabilities": {
            "windowsWorkloads": 50,
            "sqlServerSupport": 40,
            "entraIdIntegration": 18,
            "microsoftEcosystem": 22,
            "hybridConnectivity": 60,
            "kubernetes": 78,
            "serverlessContainers": 68,
            "gpuInference": 72,
            "websocketsRealtime": 82,
            "mediaProcessing": 88,
            "relationalPostgres": 80,
            "relationalMySQL": 80,
            "oracleDatabase": 20,
            "cachingRedis": 78,
            "scheduledJobsQueues": 75,
            "developerSimplicity": 78,
            "costEfficiencyPerDollar": 92,
            "complianceCoverage": ["gdpr", "hipaa", "pci-dss"],
            "regions": ["europe", "us-east"]
        },
        "services": {
            "dns": "OVH DNS",
            "loadBalancer": "OVH Load Balancer",
            "compute": "Public Cloud Instances & Bare Metal Servers",
            "containerOrchestrator": "Managed Kubernetes Service (MKS)",
            "serverless": "OVH AI Endpoints",
            "database": {
                "sqlServer": "Self-managed on VM",
                "postgres": "OVH Managed Databases for PostgreSQL",
                "mysql": "OVH Managed Databases for MySQL",
                "oracle": "Not Supported",
                "nosql": "Managed MongoDB"
            },
            "cache": "OVH Managed Redis",
            "objectStorage": "High Performance Object Storage (S3 API)",
            "queue": "Managed Kafka / RabbitMQ",
            "scheduledJobs": "Cron on Public Cloud",
            "gpuInstance": "GPU Instances (NVIDIA V100S / A100)",
            "hybridGateway": "OVHcloud Connect",
            "identity": "IAM OVHcloud",
            "monitoring": "Metrics Data Platform",
            "cdn": "OVH CDN",
            "security": "Proprietary Anti-DDoS (VAC)"
        },
        "pricing": {
            "computePerHourVCPU": 0.0140,
            "ramPerHourGB": 0.0022,
            "dbBaseMonthly": 12.00,
            "sqlServerLicenseMultiplier": 2.80,
            "objectStoragePerGBMonth": 0.010,
            "egressPerGB": 0.000,
            "cacheBaseMonthly": 12.00,
            "gpuHourlyRate": 0.90,
            "hybridGatewayMonthly": 35.00
        },
        "pros": [
            "100% unmetered and unlimited outbound bandwidth with zero egress surcharges",
            "Built-in proprietary hardware Anti-DDoS scrubbing centers",
            "Shielded from US surveillance laws and strict EU data privacy compliance"
        ],
        "cons": [
            "Complex administrative console and slower customer support ticketing",
            "Requires careful multi-region disaster recovery planning"
        ],
        "bestFor": "Game servers (Minecraft, Steam), video streaming mirrors, large file distribution, European privacy"
    },
    {
        "id": "alibaba",
        "name": "Alibaba Cloud (Aliyun)",
        "shortName": "Alibaba Cloud",
        "category": "Hyperscaler (APAC Leader)",
        "badge": "Mainland China & APAC Dominance",
        "country": "China / APAC / Global (India region)",
        "starterSpec": "1 vCPU, 2 GB RAM, 60 GB SSD",
        "tagline": "The dominant cloud across Mainland China and APAC with native ICP license support.",
        "description": "Alibaba Cloud is the undisputed market leader across China and Southeast Asia, offering seamless penetration through the Great Firewall and dedicated cross-border express lines.",
        "costMonthlyUSD": 6.00,
        "cost24HrUSD": 0.22,
        "freeAllowance": "$300 to $1,000 corporate trial credits + 12-month free usage tier",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "Regional metered allowances",
        "capabilities": {
            "windowsWorkloads": 70,
            "sqlServerSupport": 72,
            "entraIdIntegration": 30,
            "microsoftEcosystem": 35,
            "hybridConnectivity": 85,
            "kubernetes": 90,
            "serverlessContainers": 85,
            "gpuInference": 92,
            "websocketsRealtime": 85,
            "mediaProcessing": 90,
            "relationalPostgres": 88,
            "relationalMySQL": 95,
            "oracleDatabase": 60,
            "cachingRedis": 90,
            "scheduledJobsQueues": 88,
            "developerSimplicity": 68,
            "costEfficiencyPerDollar": 78,
            "complianceCoverage": ["soc2", "pci-dss", "gdpr"],
            "regions": ["apac", "india", "europe", "us-east"]
        },
        "services": {
            "dns": "Alibaba Cloud DNS",
            "loadBalancer": "Server Load Balancer (SLB)",
            "compute": "Elastic Compute Service (ECS)",
            "containerOrchestrator": "Container Service for Kubernetes (ACK)",
            "serverless": "Function Compute (FC)",
            "database": {
                "sqlServer": "ApsaraDB RDS for SQL Server",
                "postgres": "ApsaraDB RDS for PostgreSQL / PolarDB",
                "mysql": "PolarDB for MySQL",
                "oracle": "PolarDB Migration Engine",
                "nosql": "ApsaraDB for MongoDB / Tablestore"
            },
            "cache": "ApsaraDB for Redis",
            "objectStorage": "Object Storage Service (OSS)",
            "queue": "Message Queue (RocketMQ / Kafka)",
            "scheduledJobs": "Serverless Task / SchedulerX",
            "gpuInstance": "GPU-accelerated ECS (NVIDIA A10 / V100)",
            "hybridGateway": "Express Connect & Smart Access Gateway",
            "identity": "Resource Access Management (RAM)",
            "monitoring": "CloudMonitor",
            "cdn": "Alibaba Cloud DCDN",
            "security": "Anti-DDoS Pro & Web Application Firewall"
        },
        "pricing": {
            "computePerHourVCPU": 0.0250,
            "ramPerHourGB": 0.0035,
            "dbBaseMonthly": 20.00,
            "sqlServerLicenseMultiplier": 2.10,
            "objectStoragePerGBMonth": 0.018,
            "egressPerGB": 0.075,
            "cacheBaseMonthly": 18.00,
            "gpuHourlyRate": 1.10,
            "hybridGatewayMonthly": 55.00
        },
        "pros": [
            "Unrivaled infrastructure across Mainland China and Southeast Asia",
            "Full enterprise assistance with Chinese ICP operating licenses",
            "High performance PolarDB cloud-native database engine"
        ],
        "cons": [
            "Complex regulatory compliance under Chinese cybersecurity law",
            "English documentation can feature uneven translations"
        ],
        "bestFor": "E-commerce and mobile apps expanding into China, Hong Kong, and Southeast Asia"
    },
    {
        "id": "scaleway",
        "name": "Scaleway",
        "shortName": "Scaleway",
        "category": "Alternative IaaS",
        "badge": "Apple Silicon Mac Cloud & Green IaaS",
        "country": "France / Netherlands / Poland",
        "starterSpec": "1 vCPU, 2 GB RAM, 20 GB Block",
        "tagline": "European green cloud hosting, hourly bare-metal Apple Silicon M-series Macs, and modern developer PaaS.",
        "description": "Scaleway provides 100% renewable powered cloud hosting across Paris, Amsterdam, and Warsaw, complete with managed Kubernetes, Serverless, and hourly Apple Silicon Macs.",
        "costMonthlyUSD": 7.20,
        "cost24HrUSD": 0.26,
        "freeAllowance": "€100 promo vouchers + permanent free tier for 1M serverless executions & 75 GB S3 storage",
        "creditCardReq": "Yes",
        "bandwidthIncluded": "Generous EU bandwidth pools",
        "capabilities": {
            "windowsWorkloads": 25,
            "sqlServerSupport": 20,
            "entraIdIntegration": 10,
            "microsoftEcosystem": 15,
            "hybridConnectivity": 35,
            "kubernetes": 80,
            "serverlessContainers": 82,
            "gpuInference": 75,
            "websocketsRealtime": 80,
            "mediaProcessing": 80,
            "relationalPostgres": 82,
            "relationalMySQL": 80,
            "oracleDatabase": 10,
            "cachingRedis": 80,
            "scheduledJobsQueues": 76,
            "developerSimplicity": 90,
            "costEfficiencyPerDollar": 86,
            "complianceCoverage": ["gdpr", "hipaa"],
            "regions": ["europe"]
        },
        "services": {
            "dns": "Scaleway Domains & DNS",
            "loadBalancer": "Scaleway Load Balancer",
            "compute": "Instances & Bare Metal (inc. Apple Silicon M2/M3)",
            "containerOrchestrator": "Kubernetes Kapsule / Kosmos",
            "serverless": "Serverless Containers & Functions",
            "database": {
                "sqlServer": "Self-managed on VM",
                "postgres": "Managed PostgreSQL Database",
                "mysql": "Managed MySQL Database",
                "oracle": "Not Supported",
                "nosql": "Managed Redis"
            },
            "cache": "Managed Redis",
            "objectStorage": "Scaleway Object Storage (Multi-AZ)",
            "queue": "Managed Messaging (SQS/NATS)",
            "scheduledJobs": "Serverless Cron Triggers",
            "gpuInstance": "GPU Instances (NVIDIA H100 / L40S)",
            "hybridGateway": "Private Network & VPC",
            "identity": "Scaleway IAM",
            "monitoring": "Cockpit (Managed Grafana)",
            "cdn": "Scaleway Edge Services",
            "security": "Secret Manager & Security Groups"
        },
        "pricing": {
            "computePerHourVCPU": 0.0150,
            "ramPerHourGB": 0.0024,
            "dbBaseMonthly": 14.00,
            "sqlServerLicenseMultiplier": 3.00,
            "objectStoragePerGBMonth": 0.015,
            "egressPerGB": 0.010,
            "cacheBaseMonthly": 14.00,
            "gpuHourlyRate": 0.95,
            "hybridGatewayMonthly": 20.00
        },
        "pros": [
            "Bare-metal Apple Silicon M-series Mac instances by the hour for iOS/macOS CI/CD",
            "100% renewable-powered European datacenters with low PUE rating",
            "Integrated Grafana Cockpit and modern developer-first console"
        ],
        "cons": [
            "Geographic coverage restricted to Europe (Paris, Amsterdam, Warsaw)",
            "Smaller global community than the Big 3"
        ],
        "bestFor": "iOS/macOS automated CI/CD build farms, green hosting sustainability mandates"
    },

    # --- MODERN DEVELOPER PAAS ---
    {
        "id": "render",
        "name": "Render",
        "shortName": "Render",
        "category": "Developer PaaS",
        "badge": "Zero-DevOps Git Push Simplicity",
        "country": "Global Edge (Oregon, Ohio, Frankfurt, Singapore)",
        "starterSpec": "0.5 CPU, 512 MB RAM (Starter Always-On)",
        "tagline": "Zero-DevOps Git push deploys, automatic SSL, native managed PostgreSQL, Redis, and cron jobs.",
        "description": "Render completely eliminates infrastructure maintenance with automatic Git-push builds, preview environments, and instant scalability for modern web stacks.",
        "costMonthlyUSD": 7.00,
        "cost24HrUSD": 0.23,
        "freeAllowance": "Permanent Free Tier (750 free web service hours/month + free PostgreSQL for 90 days)",
        "creditCardReq": "No (for free tier)",
        "bandwidthIncluded": "100 GB Included Bandwidth",
        "capabilities": {
            "windowsWorkloads": 10,
            "sqlServerSupport": 10,
            "entraIdIntegration": 10,
            "microsoftEcosystem": 12,
            "hybridConnectivity": 15,
            "kubernetes": 60,
            "serverlessContainers": 90,
            "gpuInference": 40,
            "websocketsRealtime": 82,
            "mediaProcessing": 75,
            "relationalPostgres": 92,
            "relationalMySQL": 70,
            "oracleDatabase": 5,
            "cachingRedis": 90,
            "scheduledJobsQueues": 92,
            "developerSimplicity": 100,
            "costEfficiencyPerDollar": 82,
            "complianceCoverage": ["soc2", "gdpr"],
            "regions": ["us-east", "us-west", "europe", "apac"]
        },
        "services": {
            "dns": "Render Custom Domains & Cloudflare DNS",
            "loadBalancer": "Built-in Zero-Config TLS Load Balancer",
            "compute": "Render Web Services & Background Workers",
            "containerOrchestrator": "Fully Managed Kubernetes Behind the Scenes",
            "serverless": "Render Background Tasks",
            "database": {
                "sqlServer": "Not Supported",
                "postgres": "Render Fully Managed PostgreSQL",
                "mysql": "Dockerized MySQL (Self-managed)",
                "oracle": "Not Supported",
                "nosql": "Dockerized NoSQL"
            },
            "cache": "Render Managed Redis",
            "objectStorage": "Integrated S3 / Cloudflare R2",
            "queue": "Render Background Workers + Redis Queue",
            "scheduledJobs": "Render Cron Jobs (Native UI Scheduler)",
            "gpuInstance": "Not natively available on starter tiers",
            "hybridGateway": "Not Supported",
            "identity": "OAuth / Auth0 / Clerk integration",
            "monitoring": "Built-in Metrics & Log Streams",
            "cdn": "Global Edge CDN",
            "security": "Automated Let's Encrypt SSL & DDoS Protection"
        },
        "pricing": {
            "computePerHourVCPU": 0.0200,
            "ramPerHourGB": 0.0040,
            "dbBaseMonthly": 7.00,
            "sqlServerLicenseMultiplier": 3.50,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.020,
            "cacheBaseMonthly": 7.00,
            "gpuHourlyRate": 1.50,
            "hybridGatewayMonthly": 50.00
        },
        "pros": [
            "Zero DevOps: Automatic Git-push deployments with instant preview URLs",
            "Integrated managed PostgreSQL and Redis configured in under 60 seconds",
            "Native cron jobs and background workers included directly in dashboard"
        ],
        "cons": [
            "Free tier instances sleep after 15 minutes of inactivity with 30-50s cold boot",
            "Persistent volumes are bound to single instances without distributed clustering"
        ],
        "bestFor": "Lean startup MVPs, Next.js / Django / Rails / FastAPI applications, agency client apps with zero sysadmin"
    },
    {
        "id": "flyio",
        "name": "Fly.io",
        "shortName": "Fly.io",
        "category": "Developer PaaS",
        "badge": "Global Edge Micro-VMs & WebSockets",
        "country": "30+ Global Edge Cities (including Mumbai)",
        "starterSpec": "1 Shared CPU, 256 MB RAM (Micro-VM)",
        "tagline": "Deploys Docker containers as micro-VMs in 30+ cities worldwide with WireGuard private mesh.",
        "description": "Fly.io transforms Docker images into lightweight Firecracker micro-VMs running close to users across 30+ global edge locations with sub-10ms response times.",
        "costMonthlyUSD": 1.94,
        "cost24HrUSD": 0.065,
        "freeAllowance": "Free resource allowance: Up to 3 micro-VMs, 3 GB persistent storage, 160 GB egress/mo free",
        "creditCardReq": "Yes (Card needed for verification)",
        "bandwidthIncluded": "160 GB Free Outbound Egress per month",
        "capabilities": {
            "windowsWorkloads": 10,
            "sqlServerSupport": 10,
            "entraIdIntegration": 10,
            "microsoftEcosystem": 12,
            "hybridConnectivity": 25,
            "kubernetes": 60,
            "serverlessContainers": 94,
            "gpuInference": 70,
            "websocketsRealtime": 98,
            "mediaProcessing": 78,
            "relationalPostgres": 86,
            "relationalMySQL": 75,
            "oracleDatabase": 5,
            "cachingRedis": 85,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 88,
            "costEfficiencyPerDollar": 90,
            "complianceCoverage": ["soc2", "gdpr"],
            "regions": ["india", "us-east", "us-west", "europe", "apac", "latam"]
        },
        "services": {
            "dns": "Fly Anycast DNS",
            "loadBalancer": "Fly Edge Proxy (Global Anycast IPv4/IPv6)",
            "compute": "Fly Machines (Firecracker Micro-VMs)",
            "containerOrchestrator": "Fly Orchestration Engine",
            "serverless": "Scale-to-Zero Fly Machines",
            "database": {
                "sqlServer": "Not Supported",
                "postgres": "Fly Postgres (LiteFS / Stolon clustered)",
                "mysql": "Self-hosted Docker Container",
                "oracle": "Not Supported",
                "nosql": "LiteFS / SQLite replicated at edge"
            },
            "cache": "Fly Redis (Upstash powered)",
            "objectStorage": "Tigris Object Storage (Global S3 API)",
            "queue": "Redis / RabbitMQ in Micro-VM",
            "scheduledJobs": "Fly Machine Scheduled Wakeups",
            "gpuInstance": "Fly GPUs (NVIDIA A100 / A10 / L40S by the second)",
            "hybridGateway": "Fly WireGuard Private Mesh Network",
            "identity": "Third-Party OAuth / Supabase",
            "monitoring": "Fly Grafana & Prometheus",
            "cdn": "Fly Edge Anycast Routing",
            "security": "Automated TLS Certificates"
        },
        "pricing": {
            "computePerHourVCPU": 0.0120,
            "ramPerHourGB": 0.0022,
            "dbBaseMonthly": 5.00,
            "sqlServerLicenseMultiplier": 3.50,
            "objectStoragePerGBMonth": 0.015,
            "egressPerGB": 0.020,
            "cacheBaseMonthly": 5.00,
            "gpuHourlyRate": 0.85,
            "hybridGatewayMonthly": 15.00
        },
        "pros": [
            "Deploys Docker containers as Firecracker micro-VMs in 30+ cities within seconds",
            "Best-in-class low latency for WebSockets, LiveView, and bidirectional streams",
            "WireGuard private mesh connects distributed services without public IP exposure"
        ],
        "cons": [
            "Primarily CLI-driven workflow (flyctl) with sparse point-and-click GUI",
            "Networking and persistent volume attachments require understanding micro-VM semantics"
        ],
        "bestFor": "Real-time multiplayer backends, Elixir/Phoenix, WebSockets, dynamic request routing at the edge"
    },
    {
        "id": "railway",
        "name": "Railway",
        "shortName": "Railway",
        "category": "Developer PaaS",
        "badge": "Visual Canvas & Ephemeral Environments",
        "country": "Global Edge (US, Europe)",
        "starterSpec": "0.2 vCPU, 512 MB RAM Container",
        "tagline": "Interactive visual canvas to drag and connect microservices with automatic Nixpacks builds.",
        "description": "Railway offers a modern infrastructure canvas where developers visually connect services, databases, and cron workers with per-second usage-based billing.",
        "costMonthlyUSD": 5.00,
        "cost24HrUSD": 0.28,
        "freeAllowance": "$5.00 one-time trial grant + $1.00/mo recurring usage credits",
        "creditCardReq": "No (for basic trial)",
        "bandwidthIncluded": "Usage-based per GB",
        "capabilities": {
            "windowsWorkloads": 10,
            "sqlServerSupport": 10,
            "entraIdIntegration": 10,
            "microsoftEcosystem": 12,
            "hybridConnectivity": 15,
            "kubernetes": 60,
            "serverlessContainers": 88,
            "gpuInference": 45,
            "websocketsRealtime": 84,
            "mediaProcessing": 75,
            "relationalPostgres": 90,
            "relationalMySQL": 85,
            "oracleDatabase": 5,
            "cachingRedis": 88,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 96,
            "costEfficiencyPerDollar": 80,
            "complianceCoverage": ["soc2", "gdpr"],
            "regions": ["us-east", "europe"]
        },
        "services": {
            "dns": "Railway Edge Domains",
            "loadBalancer": "Automated Edge Routing & SSL",
            "compute": "Railway Service Deployments",
            "containerOrchestrator": "Railway Custom Orchestrator",
            "serverless": "Railway Ephemeral Deployments",
            "database": {
                "sqlServer": "Not Supported",
                "postgres": "Railway Managed PostgreSQL Plugin",
                "mysql": "Railway Managed MySQL Plugin",
                "oracle": "Not Supported",
                "nosql": "Railway MongoDB Plugin"
            },
            "cache": "Railway Managed Redis Plugin",
            "objectStorage": "S3 Integration Plugin",
            "queue": "Worker Containers",
            "scheduledJobs": "Railway Cron Triggers",
            "gpuInstance": "Not available on basic tiers",
            "hybridGateway": "Private Networking Mesh",
            "identity": "Third-Party OAuth",
            "monitoring": "Railway Observability & Log Drain",
            "cdn": "Edge Proxies",
            "security": "Secret Variables Management"
        },
        "pricing": {
            "computePerHourVCPU": 0.0220,
            "ramPerHourGB": 0.0042,
            "dbBaseMonthly": 5.00,
            "sqlServerLicenseMultiplier": 3.50,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.050,
            "cacheBaseMonthly": 5.00,
            "gpuHourlyRate": 1.40,
            "hybridGatewayMonthly": 30.00
        },
        "pros": [
            "Intuitive visual canvas to drag, drop, and link microservices and databases",
            "Nixpacks automatically detects programming languages and builds without Dockerfiles",
            "Ephemeral staging environments generated per GitHub pull request"
        ],
        "cons": [
            "Per-second execution billing can spike if applications suffer memory leaks",
            "Limited enterprise compliance certifications"
        ],
        "bestFor": "Rapid multi-service prototyping, ephemeral GitHub PR staging environments, developer tools"
    },

    # --- PRIVATE CLOUD & HYPERVISORS ---
    {
        "id": "proxmox",
        "name": "Proxmox VE",
        "shortName": "Proxmox",
        "category": "Private Cloud",
        "badge": "Open-Source VMware Migration Leader",
        "country": "Self-Hosted / On-Premise (Zero Cloud Lock-in)",
        "starterSpec": "Hardware Dependent (Runs on standard x86 PC or Rack Server)",
        "tagline": "Open-source enterprise hypervisor combining KVM virtual machines, LXC containers, and Ceph storage.",
        "description": "Proxmox VE is the undisputed open-source alternative to VMware vSphere, eliminating recurring Broadcom subscription hikes with built-in clustering, live migration, and ZFS.",
        "costMonthlyUSD": 0.00,
        "cost24HrUSD": 0.00,
        "freeAllowance": "100% Free & Open-Source under GNU AGPLv3. Optional enterprise support €110 - €1,050/yr",
        "creditCardReq": "No",
        "bandwidthIncluded": "Unlimited (Determined by physical network hardware)",
        "capabilities": {
            "windowsWorkloads": 85,
            "sqlServerSupport": 85,
            "entraIdIntegration": 35,
            "microsoftEcosystem": 45,
            "hybridConnectivity": 90,
            "kubernetes": 75,
            "serverlessContainers": 50,
            "gpuInference": 80,
            "websocketsRealtime": 85,
            "mediaProcessing": 85,
            "relationalPostgres": 85,
            "relationalMySQL": 85,
            "oracleDatabase": 60,
            "cachingRedis": 85,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 70,
            "costEfficiencyPerDollar": 98,
            "complianceCoverage": ["gdpr", "hipaa"],
            "regions": ["on-premise", "private-datacenter"]
        },
        "services": {
            "dns": "Local DNS / Pi-hole / BIND9",
            "loadBalancer": "HAProxy / Keepalived in LXC Container",
            "compute": "KVM Virtual Machines & Lightweight LXC Containers",
            "containerOrchestrator": "k3s / Talos Linux on Proxmox VMs",
            "serverless": "Self-hosted OpenFaaS",
            "database": {
                "sqlServer": "Windows Server VM with SQL Server on ZFS NVMe",
                "postgres": "LXC Container running PostgreSQL 16",
                "mysql": "LXC Container running MySQL 8",
                "oracle": "Oracle Linux VM",
                "nosql": "ScyllaDB / MongoDB in LXC"
            },
            "cache": "Redis in dedicated LXC Container",
            "objectStorage": "MinIO / Ceph Object Gateway (S3 compatible)",
            "queue": "RabbitMQ / Apache Kafka in LXC",
            "scheduledJobs": "Cron / Systemd inside VMs",
            "gpuInstance": "PCIe GPU Passthrough (NVIDIA RTX / Tesla)",
            "hybridGateway": "Physical Fiber Cross-connect & OPNsense / pfSense",
            "identity": "Active Directory / OpenLDAP / Keycloak integration",
            "monitoring": "Proxmox Metrics Server + InfluxDB & Grafana",
            "cdn": "Cloudflare Tunnel integration",
            "security": "Proxmox Firewall & ZFS encrypted pools"
        },
        "pricing": {
            "computePerHourVCPU": 0.0000,
            "ramPerHourGB": 0.0000,
            "dbBaseMonthly": 0.00,
            "sqlServerLicenseMultiplier": 1.00,
            "objectStoragePerGBMonth": 0.000,
            "egressPerGB": 0.000,
            "cacheBaseMonthly": 0.00,
            "gpuHourlyRate": 0.00,
            "hybridGatewayMonthly": 0.00
        },
        "pros": [
            "100% Free and open-source: Eliminates 300%+ VMware subscription fee hikes",
            "Combines KVM virtual machines and lightweight LXC containers in one web GUI",
            "Built-in live clustering, automated backup server, and ZFS/Ceph storage"
        ],
        "cons": [
            "Requires physical server hardware purchase and datacenter power/cooling",
            "Software-defined networking requires Linux networking knowledge"
        ],
        "bestFor": "SMBs and mid-sized enterprises escaping 300%+ VMware Broadcom price hikes; homelabs, on-prem hardware"
    },
    {
        "id": "openstack",
        "name": "OpenStack",
        "shortName": "OpenStack",
        "category": "Private Cloud",
        "badge": "Defense, Telco & 100% Sovereignty",
        "country": "Self-Hosted / Colocated (Sovereign Infrastructure)",
        "starterSpec": "Hardware Dependent (Requires 3+ Node Enterprise Cluster)",
        "tagline": "Transforms enterprise datacenters into a sovereign private AWS with complete technology independence.",
        "description": "OpenStack is the gold standard for sovereign private clouds, telecommunications (5G NFV), defense contractors, and large organizations demanding zero third-party cloud lock-in.",
        "costMonthlyUSD": 0.00,
        "cost24HrUSD": 0.00,
        "freeAllowance": "100% Free & Open-Source under Apache 2.0. Requires physical hardware purchase",
        "creditCardReq": "No",
        "bandwidthIncluded": "Internal datacenter fabric bandwidth",
        "capabilities": {
            "windowsWorkloads": 80,
            "sqlServerSupport": 80,
            "entraIdIntegration": 30,
            "microsoftEcosystem": 40,
            "hybridConnectivity": 95,
            "kubernetes": 90,
            "serverlessContainers": 60,
            "gpuInference": 85,
            "websocketsRealtime": 85,
            "mediaProcessing": 85,
            "relationalPostgres": 85,
            "relationalMySQL": 85,
            "oracleDatabase": 70,
            "cachingRedis": 85,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 45,
            "costEfficiencyPerDollar": 88,
            "complianceCoverage": ["fedramp", "hipaa", "soc2", "gdpr", "pci-dss"],
            "regions": ["on-premise", "private-datacenter"]
        },
        "services": {
            "dns": "Designate (DNS-as-a-Service)",
            "loadBalancer": "Octavia (Load Balancer-as-a-Service)",
            "compute": "Nova (Compute Engine)",
            "containerOrchestrator": "Magnum (Kubernetes Engine)",
            "serverless": "Qinling (Function-as-a-Service)",
            "database": {
                "sqlServer": "Trove Database Service with SQL Server",
                "postgres": "Trove Database Service with PostgreSQL",
                "mysql": "Trove Database Service with MySQL",
                "oracle": "Bare Metal Ironic with Oracle Linux",
                "nosql": "Trove MongoDB / Cassandra"
            },
            "cache": "Trove Redis Plugin",
            "objectStorage": "Swift (Object Storage Service)",
            "queue": "Zaqar (Multi-Tenant Messaging)",
            "scheduledJobs": "Mistral (Workflow Service)",
            "gpuInstance": "Nova GPU vGPU / PCIe Passthrough",
            "hybridGateway": "Neutron Networking & BGP Dynamic Routing",
            "identity": "Keystone (Identity & Token Service)",
            "monitoring": "Ceilometer & Aodh (Telemetry & Alarming)",
            "cdn": "Barbican & External CDN",
            "security": "Barbican (Key Management)"
        },
        "pricing": {
            "computePerHourVCPU": 0.0000,
            "ramPerHourGB": 0.0000,
            "dbBaseMonthly": 0.00,
            "sqlServerLicenseMultiplier": 1.00,
            "objectStoragePerGBMonth": 0.000,
            "egressPerGB": 0.000,
            "cacheBaseMonthly": 0.00,
            "gpuHourlyRate": 0.00,
            "hybridGatewayMonthly": 0.00
        },
        "pros": [
            "Complete technological sovereignty: Immune to US CLOUD Act surveillance and cloud vendor lock-in",
            "Transforms hundreds of physical rack servers into an automated private AWS/Azure",
            "100% open-source software with massive telco and defense industry backing"
        ],
        "cons": [
            "Legendary operational complexity: Requires specialized full-time infrastructure engineers",
            "High upfront capital expenditure (CapEx) for physical server clusters"
        ],
        "bestFor": "Telecommunications providers (5G NFV), defense agencies, scientific research (CERN), sovereign clouds"
    },
    {
        "id": "nutanix",
        "name": "Nutanix Enterprise Cloud",
        "shortName": "Nutanix",
        "category": "Private Cloud",
        "badge": "Turnkey Enterprise Hyperconverged Cloud",
        "country": "Self-Hosted / Hybrid Multi-Cloud",
        "starterSpec": "3-Node Appliance Minimum Cluster",
        "tagline": "Turnkey enterprise hyperconverged infrastructure (HCI) with 1-click simplicity and zero downtime upgrades.",
        "description": "Nutanix delivers the public cloud operational experience inside private datacenters, eliminating complex SAN storage networks with built-in Acropolis hypervisor (AHV).",
        "costMonthlyUSD": 1600.00,
        "cost24HrUSD": 52.00,
        "freeAllowance": "Vendor test drive and evaluation cluster demos",
        "creditCardReq": "No (B2B Contract)",
        "bandwidthIncluded": "Internal HCI storage fabric",
        "capabilities": {
            "windowsWorkloads": 90,
            "sqlServerSupport": 90,
            "entraIdIntegration": 65,
            "microsoftEcosystem": 75,
            "hybridConnectivity": 95,
            "kubernetes": 88,
            "serverlessContainers": 70,
            "gpuInference": 85,
            "websocketsRealtime": 85,
            "mediaProcessing": 85,
            "relationalPostgres": 88,
            "relationalMySQL": 88,
            "oracleDatabase": 85,
            "cachingRedis": 85,
            "scheduledJobsQueues": 85,
            "developerSimplicity": 85,
            "costEfficiencyPerDollar": 70,
            "complianceCoverage": ["hipaa", "soc2", "pci-dss", "fedramp"],
            "regions": ["on-premise", "hybrid-cloud"]
        },
        "services": {
            "dns": "Nutanix Flow DNS",
            "loadBalancer": "Integrated Flow Virtual Networking",
            "compute": "AHV (Acropolis Hypervisor) Virtual Machines",
            "containerOrchestrator": "Nutanix Kubernetes Engine (NKE)",
            "serverless": "Nutanix Cloud Native integrations",
            "database": {
                "sqlServer": "Nutanix Database Service (NDB) for SQL Server",
                "postgres": "Nutanix Database Service (NDB) for PostgreSQL",
                "mysql": "Nutanix Database Service (NDB) for MySQL",
                "oracle": "Nutanix Database Service (NDB) for Oracle RAC",
                "nosql": "Nutanix Objects / NoSQL"
            },
            "cache": "NDB Redis deployment",
            "objectStorage": "Nutanix Objects (S3-compatible)",
            "queue": "Kafka on Nutanix",
            "scheduledJobs": "Prism Pro Automation Workflows",
            "gpuInstance": "Virtual GPU (vGPU) on Nutanix AHV",
            "hybridGateway": "Nutanix Cloud Clusters (NC2) on AWS/Azure",
            "identity": "Active Directory / Entra ID Federation",
            "monitoring": "Prism Central with Machine Learning Operations",
            "cdn": "Third-Party Edge integration",
            "security": "Flow Microsegmentation & Data-at-Rest Encryption"
        },
        "pricing": {
            "computePerHourVCPU": 0.0500,
            "ramPerHourGB": 0.0070,
            "dbBaseMonthly": 50.00,
            "sqlServerLicenseMultiplier": 1.50,
            "objectStoragePerGBMonth": 0.020,
            "egressPerGB": 0.000,
            "cacheBaseMonthly": 35.00,
            "gpuHourlyRate": 1.50,
            "hybridGatewayMonthly": 100.00
        },
        "pros": [
            "1-Click operational simplicity: Software, hypervisor, and firmware updates with zero application downtime",
            "Eliminates complex Fibre Channel SAN storage arrays with distributed virtual storage fabric",
            "Hybrid multi-cloud mobility: Run exact same VMs on-premise or natively in AWS/Azure (NC2)"
        ],
        "cons": [
            "High upfront capital expenditure: Commercial software licensing and hardware appliances",
            "Proprietary hyperconverged software stack"
        ],
        "bestFor": "Mid-market to large enterprises seeking a turn-key private cloud without OpenStack management complexity"
    }
]

def get_provider_by_id(provider_id: str) -> Dict[str, Any]:
    """Retrieve provider data by ID or return first as fallback."""
    for p in CLOUD_PROVIDERS:
        if p["id"].lower() == provider_id.lower():
            return p
    return CLOUD_PROVIDERS[0]
